# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-07 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='status',
        ),
    ]
