# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-18 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_remove_track_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='media_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
