# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_media_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
