# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_track_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='media_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
