language: python
python:
  - "2.7"
services: postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE band_maker;" - U postgres
script:
  - python manage.py migrate
  - python manage.py test