language: python
python:
  - "3.5"
services: postgresql
install:
  - pip3 install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE melody_buddy;" -U postgres
script:
  - python3 manage.py migrate
  - python3 manage.py test