# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
