# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-27 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20161027_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='audio_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
