# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-27 04:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_composer'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 27, 4, 11, 1, 32127, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 27, 4, 11, 3, 880029, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
