# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-31 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20161027_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackrequest',
            name='audio_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='audio_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
