# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-27 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20160927_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='media_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
