# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-01 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20161031_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='license',
            field=models.CharField(choices=[(b'cc-by-4.0', b'Creative Commons Attribution 4.0')], default=b'cc-by-4.0', max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='license',
            field=models.CharField(choices=[(b'cc-by-4.0', b'Creative Commons Attribution 4.0')], default=b'cc-by-4.0', max_length=100),
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='license',
            field=models.CharField(choices=[(b'cc-by-4.0', b'Creative Commons Attribution 4.0')], default=b'cc-by-4.0', max_length=100),
        ),
    ]
