# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-09 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20161101_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='license',
            field=models.CharField(choices=[('cc-by-4.0', 'Creative Commons Attribution 4.0')], default='cc-by-4.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='license',
            field=models.CharField(choices=[('cc-by-4.0', 'Creative Commons Attribution 4.0')], default='cc-by-4.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='trackrequest',
            name='license',
            field=models.CharField(choices=[('cc-by-4.0', 'Creative Commons Attribution 4.0')], default='cc-by-4.0', max_length=100),
        ),
    ]
