# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-28 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20160928_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='instrument',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='media_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='media_url',
            field=models.CharField(max_length=500),
        ),
    ]
