# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-28 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20160928_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='media_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
