# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-12 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_auto_20161212_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='tracks',
        ),
        migrations.AddField(
            model_name='track',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='songs.Song'),
            preserve_default=False,
        ),
    ]
