# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_auto_20161212_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='instrument',
            field=models.CharField(choices=[('rhythm_guitar', 'Rhythm Guitar'), ('lead_guitar', 'Lead Guitar'), ('bass_guitar', 'Bass Guitar')], max_length=100),
        ),
    ]
