# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-06 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_auto_20161006_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='composer',
            new_name='created_by',
        ),
    ]
