# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-14 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_auto_20161214_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='instrument',
            field=models.CharField(choices=[('Bass', (('acoustic_bass_guitar', 'Acoustic Bass Guitar'), ('double_bass', 'Double Bass'), ('bass_guitar', 'Bass Guitar'))), ('Guitar', (('acoustic_guitar', 'Acoustic Guitar'), ('classical_guitar', 'Classical Guitar'), ('electric_guitar', 'Electric Guitar'), ('steel_guitar', 'Steel Guitar')))], max_length=100),
        ),
    ]
