# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_auto_20161007_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
