# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-14 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0013_auto_20161214_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='contributed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
