# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_song_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
