# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_track_contributed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
