# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_auto_20161021_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
