# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0016_trackrequest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trackrequest',
            table='track_requests',
        ),
    ]
